# Generated by Django 5.1 on 2024-11-24 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_review_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='order_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.orderitem'),
        ),
    ]
